### PR TITLE
Use core's phpcs

### PR DESCRIPTION
**Pull request by cilefen**
With https://www.drupal.org/node/2744463 in, use core's phpcs.

### CODE REVIEW

**Comment by wimleers** [comment]
EXCITING!

**Comment by cilefen** [comment]
No way to tell if sarcasm...

**Comment by wimleers** [comment]
I was very serious :) It's great that we can switch this to use core's phpcs.xml!

**Comment by alexpott** [comment]
We should change the message about missing phpcs to tell users to run composer install.

**Comment by alexpott** [comment]
Going to merge this and update the message myself.

**Pull request merged**
