### PR TITLE
Fail hard if dependent executables are not available in pre-commit

### PR DESCRIPTION
**Pull request by cilefen**

### CODE REVIEW

**Comment by wimleers** [comment]
lgtm

**Comment by cilefen** [comment]
I had to google IGTM. If phpcs is not installed, there is a echoed warning but the commit proceeds.

**Comment by alexpott** [comment]
When I wrote this I was like we shouldn't prevent a commit if stuff is missing. Do we think we should change this and prevent a commit?

**Comment by lauriii** [comment]
I think I would prefer preventing making a commit if dependencies are missing. Otherwise one might accidentally commit something they didn't mean to.

If someone feels like living on the edge and wants to ignore the hooks, they should use `--no-verify` flag. Then they explicitly make a decision to ignore the best practices which potentially is required sometimes.

**Pull request merged**
